<a href="https://colab.research.google.com/github/wilsonmarundaa-netizen/updated-flyRank-intern/blob/main/w04_baseline_score.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ML-07 — Baseline Action Score and Top-20 Review

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/wilsonmarundaa-netizen/updated-flyRank-intern/blob/main/work/notebooks/w04_baseline_score.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. My rule and its reason codes

*Write the rule in plain words first. Then the reason codes it can output.*

The rule: Pages with declining traffic should be prioritized for review.

In [ ]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## 2. Build the ranked queue (writes the CSV)

*Code the score, rank everything, write work/outputs/baseline_action_score.csv.*

In [ ]:
!wget https://raw.githubusercontent.com/wilsonmarundaa-netizen/updated-flyRank-intern/main/data/raw/content_refresh_anonymized.csv

import pandas as pd

df = pd.read_csv('content_refresh_anonymized.csv')



df.info()

--2026-08-19 19:41:30--  https://raw.githubusercontent.com/wilsonmarundaa-netizen/updated-flyRank-intern/main/data/raw/content_refresh_anonymized.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.108.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6727670 (6.4M) [text/plain]
Saving to: ‘content_refresh_anonymized.csv’

content_refresh_ano 100%[===================>]   6.42M  --.-KB/s    in 0.02s

2026-08-19 19:41:30 (336 MB/s) - ‘content_refresh_anonymized.csv’ saved [6727670/6727670]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 44 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   content_id              30000 non-null  object
 1   client_id               30000 non-null  object
 2   search_volume           27532 non-null  float64
 3   competition             27532 non-null  float64
 4   competition_level       27390 non-null  object
 5   cpc                     27532 non-null  float64
 6   content_type            30000 non-null  object
 7   main_intent             27626 non-null  object
 8   word_count              22301 non-null  float64
 9   char_count              22301 non-null  float64
 10  provider_used           8562 non-null   object
 11  model_used              24267 non-null  object
 12  impressions_90d         30000 non-null  int64
 13  clicks_90d              30000 non-null  int64
 14  pageviews_90d           30000 non-null  int64
 15  sessions_90d            30000 non-null  int64
 16  users_90d               30000 non-null  int64
 17  engaged_sessions_90d    30000 non-null  int64
 18  ai_sessions_90d         30000 non-null  int64
 19  scroll_events_90d       30000 non-null  int64
 20  days_with_impressions   30000 non-null  int64
 21  days_with_sessions      30000 non-null  int64
 22  impressions_last_30d    30000 non-null  int64
 23  clicks_last_30d         30000 non-null  int64
 24  sessions_last_30d       30000 non-null  int64
 25  impressions_prev_30d    30000 non-null  int64
 26  clicks_prev_30d         30000 non-null  int64
 27  sessions_prev_30d       30000 non-null  int64
 28  content_age_days        30000 non-null  int64
 29  age_tier                30000 non-null  object
 30  age_tier_order          30000 non-null  int64
 31  days_since_last_update  30000 non-null  int64
 32  freshness_tier          30000 non-null  object
 33  word_count_tier         22301 non-null  object
 34  char_count_tier         22301 non-null  object
 35  ctr                     30000 non-null  float64
 36  avg_position            30000 non-null  float64
 37  engagement_rate         30000 non-null  float64
 38  scroll_rate             29875 non-null  float64
 39  ai_traffic_pct          30000 non-null  float64
 40  impression_tier         30000 non-null  object
 41  position_tier           30000 non-null  object
 42  trend_direction         30000 non-null  object
 43  trend_pct               26612 non-null  float64
dtypes: float64(11), int64(19), object(14)
memory usage: 10.1+ MB

In [ ]:
df["trend_direction"].unique()

array(['down', 'stable', 'new', 'up', 'flat'], dtype=object)

In [ ]:
df["down_trend"] = df["trend_direction"] == "down"

In [ ]:
df["impressions_90d"].mean()

np.float64(5200.3663)

In [ ]:
import numpy as np

df["impressions_30d_rate"] = df["impressions_last_30d"] / 30
df["impressions_90d_rate"] = df["impressions_90d"] / 90

df["score"] = np.where(
    df["impressions_30d_rate"] > df["impressions_90d_rate"],
    "up",
    "down"
)
df["score"]

0        down
18545    down
18525    down
18526    down
18527    down
18528    down
18529    down
18530    down
18531    down
18533    down
18534    down
18535    down
18536    down
18537    down
18538    down
18539    down
18540    down
18541    down
18543    down
18520    down
Name: score, dtype: object

In [ ]:
df = df.sort_values("score", ascending=False).head(20)
df[["content_id","score","impressions_90d","impressions_last_30d","impressions_30d_rate","impressions_90d_rate"]]

,content_id,score,impressions_90d,impressions_last_30d,impressions_30d_rate,impressions_90d_rate
0,content_304f48230142,down,3803,578,19.266667,42.255556
18545,content_ee78be242093,down,196,47,1.566667,2.177778
18543,content_bf7b1ebef464,down,12,3,0.100000,0.133333
18541,content_a87f07530a71,down,39,9,0.300000,0.433333
18540,content_f7c3e75bbcb2,down,14813,2334,77.800000,164.588889
18539,content_f3c49edd9c15,down,20,1,0.033333,0.222222
18538,content_e5fe2f1d01f9,down,1538,126,4.200000,17.088889
18537,content_bc805f67c328,down,26,4,0.133333,0.288889
18536,content_93f8f0b760af,down,1124,183,6.100000,12.488889
18535,content_aed858812e1e,down,607,184,6.133333,6.744444
18534,content_62c3c0d4ec61,down,2669,799,26.633333,29.655556
18533,content_8dcc9ba9e983,down,422,78,2.600000,4.688889
18531,content_d10f9ce1e0cd,down,166,47,1.566667,1.844444
18530,content_fd276e6d3b9d,down,651,125,4.166667,7.233333
18529,content_6adb914d0e05,down,1,0,0.000000,0.011111
18528,content_77b38e6cb53b,down,762,33,1.100000,8.466667
18527,content_b275238955fe,down,548,118,3.933333,6.088889
18526,content_c55756d2a06f,down,192,13,0.433333,2.133333
18525,content_2a8a36c089cd,down,17399,4063,135.433333,193.322222
18520,content_1adccaeec203,down,2,0,0.000000,0.022222

## 3. Top-20 review

*For each of the top 20: action, reason code, confidence note, and what would make it wrong.*

Actions that could be taken: refresh, expansion, protection, pruning or monitoring

In [ ]:
import numpy as np

df["action"] = np.select(
    [
        df["score"] == "up",
        df["score"] == "down",

    ],
    [

        "Monitoring/Protection",
        "Pruning/Refresh",
    ],
    default="Monitoring"
)

df[["content_id","score","impressions_90d","action"]]

                 content_id score  impressions_90d           action
0      content_304f48230142  down             3803  Pruning/Refresh
18545  content_ee78be242093  down              196  Pruning/Refresh
18543  content_bf7b1ebef464  down               12  Pruning/Refresh
18541  content_a87f07530a71  down               39  Pruning/Refresh
18540  content_f7c3e75bbcb2  down            14813  Pruning/Refresh
18539  content_f3c49edd9c15  down               20  Pruning/Refresh
18538  content_e5fe2f1d01f9  down             1538  Pruning/Refresh
18537  content_bc805f67c328  down               26  Pruning/Refresh
18536  content_93f8f0b760af  down             1124  Pruning/Refresh
18535  content_aed858812e1e  down              607  Pruning/Refresh
18534  content_62c3c0d4ec61  down             2669  Pruning/Refresh
18533  content_8dcc9ba9e983  down              422  Pruning/Refresh
18531  content_d10f9ce1e0cd  down              166  Pruning/Refresh
18530  content_fd276e6d3b9d  down              651  Pruning/Refresh
18529  content_6adb914d0e05  down                1  Pruning/Refresh
18528  content_77b38e6cb53b  down              762  Pruning/Refresh
18527  content_b275238955fe  down              548  Pruning/Refresh
18526  content_c55756d2a06f  down              192  Pruning/Refresh
18525  content_2a8a36c089cd  down            17399  Pruning/Refresh
18520  content_1adccaeec203  down                2  Pruning/Refresh

## 4. Weak picks + leakage check

*Which picks look wrong and why? Confirm no product flags or future windows leaked in.*

In [ ]:
df[["content_id","score","impressions_last_30d","impressions_90d","impressions_30d_rate","impressions_90d_rate","trend_direction","action"]]

,content_id,score,impressions_last_30d,impressions_90d,impressions_30d_rate,impressions_90d_rate,trend_direction,action
0,content_304f48230142,down,578,3803,19.266667,42.255556,down,Pruning/Refresh
18545,content_ee78be242093,down,47,196,1.566667,2.177778,down,Pruning/Refresh
18543,content_bf7b1ebef464,down,3,12,0.100000,0.133333,down,Pruning/Refresh
18541,content_a87f07530a71,down,9,39,0.300000,0.433333,down,Pruning/Refresh
18540,content_f7c3e75bbcb2,down,2334,14813,77.800000,164.588889,down,Pruning/Refresh
18539,content_f3c49edd9c15,down,1,20,0.033333,0.222222,down,Pruning/Refresh
18538,content_e5fe2f1d01f9,down,126,1538,4.200000,17.088889,down,Pruning/Refresh
18537,content_bc805f67c328,down,4,26,0.133333,0.288889,stable,Pruning/Refresh
18536,content_93f8f0b760af,down,183,1124,6.100000,12.488889,down,Pruning/Refresh
18535,content_aed858812e1e,down,184,607,6.133333,6.744444,down,Pruning/Refresh
18534,content_62c3c0d4ec61,down,799,2669,26.633333,29.655556,stable,Pruning/Refresh
18533,content_8dcc9ba9e983,down,78,422,2.600000,4.688889,down,Pruning/Refresh
18531,content_d10f9ce1e0cd,down,47,166,1.566667,1.844444,stable,Pruning/Refresh
18530,content_fd276e6d3b9d,down,125,651,4.166667,7.233333,stable,Pruning/Refresh
18529,content_6adb914d0e05,down,0,1,0.000000,0.011111,flat,Pruning/Refresh
18528,content_77b38e6cb53b,down,33,762,1.100000,8.466667,down,Pruning/Refresh
18527,content_b275238955fe,down,118,548,3.933333,6.088889,down,Pruning/Refresh
18526,content_c55756d2a06f,down,13,192,0.433333,2.133333,down,Pruning/Refresh
18525,content_2a8a36c089cd,down,4063,17399,135.433333,193.322222,down,Pruning/Refresh
18520,content_1adccaeec203,down,0,2,0.000000,0.022222,flat,Pruning/Refresh

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.